version: '3'

services:
    db:
        image: mysql:5.7
        container_name: mysql_host
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: sakila
            MYSQL_USER: docker
            MYSQL_PASSWORD: docker
            TZ: 'Asia/Tokyo'
        volumes:
            - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
            - ./db/sql:/docker-entrypoint-initdb.d
        ports:
            - 13306:3306